#!/bin/bash

runtests () {
  export numberOfUsers=$1
  export totalEvents=$2

  echo "Users  = $1"
  echo "Events = $2"

  python follower-server.py &
  { ./followermaze.sh && echo "Test passed"; } || { echo "Test failed" && exit 1; }
}

# caveat emptor: minimally tested on GNU, works reliably on Mac OS X
cleanup () {
  echo; echo "**********************************************************"; echo
  ps -ef | grep -e "[Pp]ython [Ff]ollower-server.py" | awk '{print $2}' | xargs kill -9
}

logLevel=debug

# runtests $USERS $EVENTS
runtests 1 1
cleanup

# slightly more interesting
runtests 4 10
cleanup

# ever more slightly
runtests 10 100
cleanup

# barely scratching the surface
runtests 100 1000
cleanup

# this might hurt
runtests 1000 10000
cleanup

# hold on to your hats
unset numberOfUsers
unset totalEvents
python follower-server.py &
./followermaze.sh
cleanup
